"""Create table Category product

Revision ID: 2c9e53128176
Revises: 94e60be6d379
Create Date: 2024-12-07 19:44:45.173192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9e53128176'
down_revision = '94e60be6d379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kategori', sa.String(length=230), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_product_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_product_updated_at'))
        batch_op.drop_index(batch_op.f('ix_category_product_created_at'))

    op.drop_table('category_product')
    # ### end Alembic commands ###
